### ISSUE TITLE
Catch exceptions

### ISSUE THREAD

**Issue by cbenhagen** [rrousselGit/boundary#1]
What is the reasoning behind f81146f927bab250f3f4284f12a36a7d298e134e? Catching exceptions sounded like one of the main points of this project.

Or do I miss something and the following code should still show the fallback widget?

```dart
import 'package:boundary/boundary.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('hello')),
        body: Boundary(
          fallbackBuilder: (context, error) {
            return const Center(child: Text('Oops'));
          },
          child: Container(
            color: Colors.red,
            padding: const EdgeInsets.all(50),
            child: Builder(builder: (_) {
              throw 42;
            }),
          ),
        ),
      ),
    );
  }
}
```

**Comment by rrousselGit** [comment]
You can still make the following code by overriding `ErrorWidget.builder` to:

```dart
ErrorWidget.builder = (details) => Defer(details.exception);
FlutterError.onError = null;
```

But the library won't do it for you anymore, because this is "a bit too unsafe" to catch any exception.
By doing such code, this also catches exceptions in `initState` or similar life-cycles, which may be undesired as it leaves the throwing widget in an unstable state.

**Comment by cbenhagen** [comment]
Thanks. I am using Crashlytics to handle `FlutterError.onError`. So I will just use the first line. My main goal using this library is to provide some nice fallback on any uncaught errors which provides a way to contact support with added details about what happened instead of an ugly red screen. Hope this is one of the goals you had in mind when starting this experiment.

**Comment by rrousselGit** [comment]
> I am using Crashlytics to handle FlutterError.onError

Technically speaking, that'd become the job of this library

The current setting of `FlutterError.onError` and `ErrorWidget.builder` is basically:

```dart
Boundary(
  fallbackBuilder: (_, err) {
    FlutterError.dumbErrorToConsole(err);
    return ErrorWidget(err);
  },
  child: MaterialApp()
);
```
