### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by shyndman** [rrousselGit/boundary#2]
Hi Remi,

I know this library is experimental and all that, but would it be possible to add a license?

Thanks :)

**Comment by rrousselGit** [comment]
Sure. Are you planing on using it? 🙂

**Comment by shyndman** [comment]
Yep, with modification as I need it. Anything I should be aware of?

**Comment by shyndman** [comment]
It's an excellent starting point, and solves an immediate issue. :)

**Comment by rrousselGit** [comment]
None that I can think of immediately.
But I do not guarantee that you won't have unexpected behavior. I haven't battle-tested it.

Feel free to create some issues/pull requests as you need.  I could make an alpha release. I find this project interesting and will likely continue to work on it at some point. 😄

**Comment by shyndman** [comment]
👍 

Thanks!
