### ISSUE TITLE
Are boundaries impossible?

### ISSUE THREAD

**Issue by lulupointu** [rrousselGit/boundary#5]
Hi,

I see that this project is still experimental, do you have any plan to make a stable version? 

If not do you have any idea how you could approach this? I mean overlay is not ideal because you might create a duplicate GlobalKey right?

I saw your discussion with the flutter team about enabling support for boundaries, especially to handle error in the build method. As you mentioned, this is sometimes used as a feature is React and I think I need this for one of my project.

**Comment by rrousselGit** [comment]
Hello!

This is more a time issue. 
I plan on resuming working on this at some point. But for now my focus in on devtools for provider

**Comment by lulupointu** [comment]
Oh ok great! I look forward to that, thanks !
